# sudo apt install nfs-kernel-server
- name: Install nfs-server package
  become: true
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes
  tags: [ setup, packages, server ]

# sudo apt install nfs-common
- name: Install nfs-server package
  become: true
  apt:
    name: nfs-common
    state: present
    update_cache: yes
  tags: [ setup, packages, client ]

# sudo ufw allow nfs
- name: Allow nfs port
  become: true
  ufw:
    port: nfs
    rule: allow
  tags: [ setup, firewall, server ]
