---

- name: Incluse os-specific backup
  tags: [ never, backup ]
  include: "backup_{{ ansible_os_family | lower }}.yml"

- name: Check backup directory exists
  tags: [ never, backup ]
  become: true
  register: elastic_backup_folder
  stat:
    path: "{{ ELASTICSEARCH_BACKUP_PATH }}"

- name: Create backup directory
  tags: [ never, backup ]
  become: true
  when: elastic_backup_folder.stat.exists == false
  file:
    path: "{{ ELASTICSEARCH_BACKUP_PATH }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch

- name: Add or modify fstab
  tags: [ never, backup ]
  become: true
  lineinfile:
    path: /etc/fstab
    regexp: '^{{ ELASTICSEARCH_BACKUP_SERVER_IP }}:{{ ELASTICSEARCH_BACKUP_SERVER_PATH }} '
    line: "{{ ELASTICSEARCH_BACKUP_SERVER_IP }}:{{ ELASTICSEARCH_BACKUP_SERVER_PATH }} {{ ELASTICSEARCH_BACKUP_PATH }} nfs4 rw,_netdev,tcp 0 0"

- name: Mount
  tags: [ never, backup ]
  become: true
  command:
    cmd: mount -a
    warn: false

- name: Config path.repo
  tags: [ never, backup ]
  become: true
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^path\.repo:'
    line: 'path.repo: ["{{ ELASTICSEARCH_BACKUP_PATH }}"]'
    insertafter: '--- Paths ---'
