---

# sudo yum install nfs-utils
- name: Install nfs package
  become: true
  yum:
    name: nfs-utils
    state: present
    update_cache: yes
  tags: [ never, backup ]

# sudo firewall-cmd --permanent --add-service=nfs
- name: firewalld
  become: true
  firewalld:
    service: nfs
    permanent: yes
    state: enabled
  tags: [ never, backup ]

# sudo firewall-cmd --reload
- name: reload service firewalld
  become: true
  systemd:
    name: firewalld
    state: reloaded
  tags: [ never, backup ]
