# sudo mkdir /etc/elasticsearch/certs
# sudo chmod 2755 /etc/elasticsearch/certs
- name: Create a cert directory
  become: true
  tags: [ cert, cert_generate ]
  file:
    path: /etc/elasticsearch/certs
    state: directory
    mode: '2755'

- name: Generate cert
  include: "cert_generate.yml"
  tags: [ cert_generate ]

- name: Copy new key
  become: true
  tags: [ cert ]
  copy:
    src: "{{ item }}"
    dest: "/etc/elasticsearch/certs/"
    owner: root
    group: elasticsearch
    backup: yes
  with_items:
    - "files/certs/ca/"
    - "files/certs/{{ inventory_hostname }}/"
