- name: Config xpack.security.enabled
  become: true
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?xpack\.security\.enabled:'
    line: 'xpack.security.enabled: true'
  tags: [ config, security ]

- name: Config xpack.security.transport.ssl.enabled
  become: true
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?xpack\.security\.transport\.ssl\.enabled:'
    line: 'xpack.security.transport.ssl.enabled: true'
  tags: [ config, security ]

- name: Config xpack.security.transport.ssl.verification_mode
  become: true
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?xpack\.security\.transport\.ssl\.verification_mode:'
    line: 'xpack.security.transport.ssl.verification_mode: certificate'
  tags: [ config, security ]

- name: Config xpack.security.transport.ssl.certificate
  become: true
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?xpack\.security\.transport\.ssl\.certificate_authorities:'
    line: 'xpack.security.transport.ssl.certificate_authorities: /etc/elasticsearch/certs/ca.crt'
  tags: [ config, security ]

- name: Config xpack.security.transport.ssl.key
  become: true
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?xpack\.security\.transport\.ssl\.key:'
    line: 'xpack.security.transport.ssl.key: /etc/elasticsearch/certs/{{ inventory_hostname }}.key'
  tags: [ config, security ]

- name: Config xpack.security.transport.ssl.certificate
  become: true
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?xpack\.security\.transport\.ssl\.certificate:'
    line: 'xpack.security.transport.ssl.certificate: /etc/elasticsearch/certs/{{ inventory_hostname }}.crt'
  tags: [ config, security ]
