# sudo rpm --install https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION:-7.9.3}-x86_64.rpm
- name: Install elasticsearch package
  become: true
  yum:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ ELASTICSEARCH_VERSION }}-x86_64.rpm
    state: present
    update_cache: yes
  tags: [ setup, packages ]

# sudo sed -i 's/#MAX_LOCKED_MEMORY=/MAX_LOCKED_MEMORY=unlimited/' /etc/sysconfig/elasticsearch
- name: Add or modify MAX_LOCKED_MEMORY
  become: true
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    regexp: '^#?MAX_LOCKED_MEMORY='
    line: MAX_LOCKED_MEMORY=unlimited
  tags: [ setup ]

# sudo firewall-cmd --add-port=9200/tcp --permanent
# sudo firewall-cmd --add-port=9300/tcp --permanent
- name: firewalld
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: [ 9200/tcp, 9300/tcp ]
  tags: [ setup, firewall ]

# sudo firewall-cmd --reload
- name: reload service firewalld
  become: true
  systemd:
    name: firewalld
    state: reloaded
  tags: [ setup, firewall ]
