---

# sudo nano /etc/hosts
- name: Set hosts
  tags: [ config ]
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: "{{ item.host }}"
    line: "{{ item.ip }}\t{{ item.host }}"
  loop: "{{ ips_hosts }}"

- name: Incluse hadoop config
  include: "config_hadoop.yml"
  tags: [ config ]

- name: Incluse spark config
  include: "config_spark.yml"
  tags: [ config ]
