- name: Check hadoop exitst
  stat:
    path: /opt/hadoop
  register: stat_hadoop
  tags: [ never, start ]

- name: Start dfs
  remote_user: hadoop
  shell: /opt/hadoop/sbin/start-dfs.sh
  when: stat_hadoop.stat.exists and stat_hadoop.stat.isdir
  tags: [ never, start ]
  register: result

- debug: var=result.stdout_lines

- name: Start yarn
  remote_user: hadoop
  shell: /opt/hadoop/sbin/start-yarn.sh
  when: stat_hadoop.stat.exists and stat_hadoop.stat.isdir
  tags: [ never, start ]
  register: result

- debug: var=result.stdout_lines

- name: Check spark exitst
  stat:
    path: /opt/spark
  register: stat_spark
  tags: [ never, start ]

- name: Start history server
  remote_user: hadoop
  shell: /opt/spark/sbin/start-history-server.sh
  when: stat_spark.stat.exists and stat_spark.stat.isdir
  tags: [ never, start ]
  register: result

- debug: var=result.stdout_lines
